### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#86] opened 2021-06-10 11:38 UTC
> Related with  https://github.com/iterative/dvc.org/issues/2443 and https://github.com/iterative/dvclive/issues/45#issuecomment-858538315

The existing ["front page"]( https://dvc.org/doc/dvclive) of `dvclive` seems to be missing some important points that are mentioned in the [README of the repository ](https://github.com/iterative/dvclive#dvclive).  At the very least, we could opt for syncing both sources of information by updating the existing `dvc.org` introduction with the information present in the `README`.

---

UPDATE: Jump to https://github.com/iterative/dvclive/issues/86#issuecomment-878066013

- [x] #116

- [x] #108

- [x] #117

- [x] #119

- [x] #123

**Comment by jorgeorpinel** [comment] 2021-06-12 00:11
> missing some important points that are mentioned in the README

That is definitely related with https://github.com/iterative/dvc.org/issues/2443, in the sense that we need to figure out how mush overlap we want between the README here and the docs in https://dvc.org/doc/dvclive

> opt for syncing both sources of information

This we don't want to do. @daavoo based on that other issue, would it be possible to get a summary of the changes you think would be needed on each side? We'll figure it out later if nor cc @pared 🙂

**Comment by jorgeorpinel** [comment] 2021-06-12 00:14
TBH this looks like a duplicate of https://github.com/iterative/dvclive/issues/45#issuecomment-858560836

**Comment by daavoo** [comment] 2021-06-17 10:22
> > missing some important points that are mentioned in the README
> 
> That is definitely related with [iterative/dvc.org#2443](https://github.com/iterative/dvc.org/issues/2443), in the sense that we need to figure out how mush overlap we want between the README here and the docs in https://dvc.org/doc/dvclive
> 
> > opt for syncing both sources of information
> 
> This we don't want to do. @daavoo based on that other issue, would it be possible to get a summary of the changes you think would be needed on each side? We'll figure it out later if not cc @pared slightly_smiling_face

I see, I would need to review iterative/dvc.org#2443 in order to propose that summary of changes.

---

> TBH this looks like a duplicate of [#45 (comment)](https://github.com/iterative/dvclive/issues/45#issuecomment-858560836).

That issue seems to be focused on the changes needed in the "README" but not the ones needed in the "docs". Not sure if we should keep a separate issue for each "target" or not

**Comment by jorgeorpinel** [comment] 2021-06-22 18:38
Yup, now that https://github.com/iterative/dvclive/pull/99is done (thanks @daavoo) I guess we can keep this one to update the docs index. We'll need to come up with the plan first (based on https://github.com/iterative/dvc.org/issues/2443) 🙂

**Comment by daavoo** [comment] 2021-07-12 08:07
> We'll need to come up with the plan first (based on [iterative/dvc.org#2443](https://github.com/iterative/dvc.org/issues/2443)) slightly_smiling_face

So here is a granular proposal of changes for `dvc.org`, based on the guidelines you linked:

---

- [ ] Link [docs index](https://dvc.org/doc/dvclive)  to this repository.

Users can't reach this repository from the docs.

- [ ] Add info about `summary` files.

The docs index only mention the log files in `.tsv` format and it's integration with `dvc plots`. Include information about summary files in `.json` format and it's integration with `dvc metrics`.

- [ ] Extend "principles" to include the ones mentioned in the README.

I think the ones added in https://github.com/iterative/dvclive/pull/71 better reflect the library comparing to those currently present in the [docs index](https://dvc.org/doc/dvclive)

- [ ] Add Command/API Reference

Establish a single point for reference as this is currently duplicated in several places (some of those with outdated info https://github.com/iterative/dvc.org/issues/2498): 

https://github.com/iterative/dvclive#quick-start 
https://dvc.org/doc/dvclive/usage#initial-configuration 
https://dvc.org/doc/user-guide/experiment-management/checkpoints#registering-checkpoints-in-your-code

- [ ] Simplify Usage Guide

Ref: https://github.com/iterative/dvclive/issues/87 . 

- [ ]  Add Integrations

Document usage of existing "self-hosted" (`keras`, `xgboost`) and external (`mmcv`) integrations.

---

What do you think @jorgeorpinel ¿?

cc @pared  @dberenbaum

**Comment by pared** [comment] 2021-07-12 10:48
LGTM! Do we want to keep all of that in one place (this issue?) I think Add command/API reference might a bigger issue than other ones. Also, in this point, do you think about removing other references once this single point is established? I am asking because those three seem to have a little bit different puprose.

**Comment by dberenbaum** [comment] 2021-07-12 14:36
> Do we want to keep all of that in one place (this issue?)

I think having this issue is helpful, but also having separate issues and PRs for the individual checkboxes linking back to here would be great.

**Comment by daavoo** [comment] 2021-07-13 07:23
> I think having this issue is helpful, but also having separate issues and PRs for the individual checkboxes linking back to here would be great.
Should we create those issues in `dvc.org` or here?

**Comment by daavoo** [comment] 2021-07-13 07:28
> Also, in this point, do you think about removing other references once this single point is established? I am asking because those three seem to have a little bit different puprose.

I wouldn't remove the other references but rather update tthe content with a link to the *docs API Reference*. Probably, for each of those other references, some of the parts overlapping with the *docs API reference* could be removed and update the remaining parts focusing on the specific purpose

**Comment by dberenbaum** [comment] 2021-07-13 12:56
> Should we create those issues in `dvc.org` or here?

I think we decided recently to keep that here especially if you will be the main contributor (cc @jorgeorpinel in case I'm remembering incorrectly).

**Comment by jorgeorpinel** [comment] 2021-07-13 18:38
> we decided recently to keep that here

Yep! Better to track in the corresponding product repo even if it's currently documented in dvc.org/doc.

**Closed** 2021-08-10 07:44 UTC
Labels: documentation
