### ISSUE TITLE
`keras`: Include `learning_rate` scalar.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#255] opened 2022-05-15 08:13 UTC
The [TensorBoard callback](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard) collects and stores learning rate:

https://github.com/keras-team/keras/blob/d8fcb9d4d4dad45080ecfdd575483653028f8eda/keras/callbacks.py#L2527-L2531

**Comment by dberenbaum** [comment] 2023-03-06 22:14
Closing as duplicate of #317

**Closed by dberenbaum** 2023-03-06 22:14 UTC
Labels: enhancement, A: frameworks
