### ISSUE TITLE
generate pipeline

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#468] opened 2023-02-23 14:02 UTC
#464/#378 is only useful outside of pipelines, but adding a `.dvc` file makes the transition to pipelines harder. Instead, we could add a `dvc.yaml` pipeline with the model as an output. If inside a DVC repo, DVCLive can generate a `dvc.yaml` pipeline stage in the root of the project like:

```
stages:
  dvclive:
    cmd: python train.py
    deps:
      - train.py
    outs:
      - dvclive/metrics.json:
          cache: false
      - dvclive/plots:
          cache: false
      - model.pt
```

On `next_step`/`end`, DVCLive can do `dvc commit dvclive` to save the changes to `dvc.lock`. We may not always be able to infer the `cmd` or `deps`, but we could use a dummy `cmd` and drop `deps` in that case. It still provides a useful skeleton for transitioning to pipelines instead of making it harder to transition.

**Comment by shcheklein** [comment] 2023-02-23 17:49
Might be related to the GTO+DVC effort. If we have a global `models` section that replaces the `artifacts.yaml` file, we can drop the cmd, and don't generate the stage if it's not needed yet.

**Comment by daavoo** [comment] 2023-02-23 18:08
> only useful outside of pipelines, but adding a .dvc file makes the transition to pipelines harder.

I think `log_artifact` should not involve any pipelines.

IMO, we should not mix data and pipelines without a reason and objectively I don't see one.

We are trying to work around the limitations of DVC that might not even have any reason behind them but are just a legacy from early implementation. 
We already made changes like adding top-level `params` and breaking the old assumption that they are always `deps`.  

I am not saying that we should block anything and try to fix data and pipeline mixing in DVC, as it is deep in the roots.

However, perhaps we could find some middle-term like adding some top-level section (I would say `data`, and not make it model-specific) or even allow DVC `outs` to "overlap with" / "be dispatched to" an external `.dvc` file (`deps` already can)

**Comment by dberenbaum** [comment] 2023-02-23 19:15
Let's decide on "generate pipeline" as a standalone feature for onboarding. DVCLive has the context of the Python process and knows that certain files are dependencies and outputs. The stage won't make much sense in some cases (like a grid search happening in a notebook cell), but I think it will always be true that the file from which DVCLive runs (if any) is a dependency and the DVCLive files are outputs.

If we think that direction is useful, we might want to block `log_artifact` so that we don't have to make a breaking change. So let's decide whether this is a useful feature.

> We are trying to work around the limitations of DVC that might not even have any reason behind them but are just a legacy from early implementation.

That was my first thought, but I think `log_artifact` is really closer to pipeline outputs than a typical `dvc add` use case. They are code outputs, not some data source generated externally.

**Comment by daavoo** [comment] 2023-02-24 17:05
> DVCLive has the context of the Python process and knows that certain files are dependencies and outputs.

I can't really say without looking in depth, but I think that generating a useful `cmd` automatically would be tricky (even not possible) for realistic scenarios beyond assuming `python script.py`.

> If we think that direction is useful

What would be the added value of autogenerating a single-stage pipeline for the user being onboarded t?  `exp run` features like `--set-param`/`--queue`? 

If we manage to make `log_artifact` not interfere when transitioning to pipelines, is it worth doing the generation automatically?

**Comment by dberenbaum** [comment] 2023-02-24 18:21
> I can't really say without looking in depth, but I think that generating a useful `cmd` automatically would be tricky (even not possible) for realistic scenarios beyond assuming `python script.py`.

Agreed, the command is the least useful part. We might always use a dummy command here to make clear it's something the user should set themselves.

> What would be the added value of autogenerating a single-stage pipeline for the user being onboarded t? `exp run` features like `--set-param`/`--queue`?

Primarily, it would make it easier to modify and add more stages than if they have to start from scratch. In VS Code, we are adding buttons to create a template `dvc.yaml` file to make this step easier for users, but DVCLive might be able to do a better job since it can partially fill in the pipeline already.

Also, by committing this pseudo-stage, it would track the dependency file and all DVCLive outputs in the run cache, which are needed to properly save/reproduce the experiment.

> If we manage to make `log_artifact` not interfere when transitioning to pipelines, is it worth doing the generation automatically?

That's the question we need to answer: whether having DVCLive generate this pipeline is useful (regardless of `log_artifact`). 

Maybe @alex000kim could weigh in since he frequently works with onboarding new customers to DVC.

**Comment by shcheklein** [comment] 2023-02-24 18:32
> What would be the added value of autogenerating a single-stage pipeline for the user being onboarded t?

Btw, I plan to do a followup for this PR, and was thinking to include a better explanation for this as well. First, don't mention the pipeline, but rather try to use something people would understand - make experiments runnable and queue-able, reproducible, easier way to do hyper-param search, etc.

https://github.com/iterative/vscode-dvc/pull/3295

It feels this discussion is related and comes down to what are we trying to communicate / push users to when we generate a pipeline file, even an artificial one. In VS Code it came at least from the need to make the experiments "runnable" with a button.

I would appreciate any ideas here on this.

**Comment by daavoo** [comment] 2023-03-06 14:34
> @daavoo Can we move forward with this? 

Ok, let's make a draft and play around.

> Do you want me to take a first try at it?

Whatever you prefer.

> By only adding a cmd, you can make it executable and get benefits like pipelines, parametrization, and queueing.

If the `dvc.yaml` we generate is not at the top, then users would also need to update the paths when moving it to the top. 

> Generating a dvc.yaml stage from DVCLive can happen always when running outside of dvc exp run/repro and never when running inside those commands.

We need to add logic to check for `dvc repro`, without making changes in DVC I guess the best option would be to check the lock files

**Comment by dberenbaum** [comment] 2023-03-07 20:31
See https://github.com/iterative/dvclive/pull/490#issuecomment-1458747287 for more context

**Comment by dberenbaum** [comment] 2023-03-08 20:36
Discussed with @daavoo that after trying to start working on and documenting this feature, it feels like it will be too hard to explain with too much unexpected behavior. Maybe in the future, we will have a cleaner way to do it, but let's not block #464  any longer.

**Comment by dberenbaum** [comment] 2023-03-09 20:48
New idea: let's print what the stage should look like during `live.end()` so that users can copy and paste into `dvc.yaml`. For example:


```
Put this into `/Users/dave/Code/myproject/dvc.yaml` to run experiments with DVC:

stages:
  dvclive:
    cmd: # Insert command to run the code
    deps:
      - train.py
    outs:
      - dvclive/metrics.json:
          cache: false
      - dvclive/plots:
          cache: false
      - model.pt

See https://dvc.org/doc/user-guide/experiment-management/running-experiments.
```

**Comment by shcheklein** [comment] 2023-03-09 20:50
`to run experiments with DVC` - can we explain the benefits better? (queue and background experiments? automating via CI/CD make them reproducible? cache results? what else?) ... asking, since we need this in VS Code as well.

**Comment by dberenbaum** [comment] 2023-03-09 21:38
> `to run experiments with DVC` - can we explain the benefits better? (queue and background experiments? automating via CI/CD make them reproducible? cache results? what else?) ... asking, since we need this in VS Code as well.

Yeah, we can think on it, but I think it will be hard to squeeze into the logger output 😄 . We should also focus on this for https://github.com/iterative/dvc.org/pull/4375.

**Comment by shcheklein** [comment] 2023-03-09 23:02
Heh, I didn't mean it literally :) Just something more explicit than "run experiments" would do the thing.

**Closed** 2023-03-20 09:38 UTC
Labels: p1-important, A: dvc, A: log_artifact
